---
- name: Check if Supabase folder exists
  ansible.builtin.stat:
    path: "/home/{{ deploy_user }}/supabase"
  register: supabase_dir

- name: Clone Supabase
  ansible.builtin.git:
    repo: https://github.com/supabase/supabase
    dest: "/home/{{ deploy_user }}/supabase"
    depth: 1
  when: not supabase_dir.stat.exists

- name: Ensure correct ownership
  ansible.builtin.file:
    path: "/home/{{ deploy_user }}/supabase"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    recurse: yes

- name: Ensure /var/log/postgresql directory exists
  ansible.builtin.file:
    path: /var/log/postgresql
    state: directory
    owner: "105"
    group: "106"
    mode: "0755"

- name: Ensure Supabase data directory exists
  ansible.builtin.file:
    path: "{{ supabase_data_path }}"
    state: directory
    owner: "105"
    group: "106"
    mode: '0755'

- name: Check if Caddy certificate exists
  ansible.builtin.stat:
    path: "{{ caddy_cert_base_path }}/{{ postgres_domain }}/{{ postgres_domain }}.crt"
  register: caddy_cert

- name: Ensure Certs directory exists
  ansible.builtin.file:
    path: "{{ postgres_cert_path }}"
    state: directory
    owner: "105"
    group: "106"
    mode: "0755"

- name: Copy Postgres SSL certificate
  ansible.builtin.copy:
    src: "{{ caddy_cert_base_path }}/{{ postgres_domain }}/{{ postgres_domain }}.crt"
    dest: "{{ postgres_cert_path }}/server.crt"
    remote_src: yes
    owner: "105"
    group: "106"
    mode: "0644"
  when: caddy_cert.stat.exists

- name: Copy Postgres SSL key
  ansible.builtin.copy:
    src: "{{ caddy_cert_base_path }}/{{ postgres_domain }}/{{ postgres_domain }}.key"
    dest: "{{ postgres_cert_path }}/server.key"
    remote_src: yes
    owner: "105"
    group: "106"
    mode: "0600"
  when: caddy_cert.stat.exists

- name: Validate Postgres cert exists
  stat:
    path: "{{ postgres_cert_path }}/server.crt"
  register: pg_cert

- name: Generate self-signed cert if Caddy's cert is missing
  command: >
    openssl req -x509 -nodes -days 365
    -newkey rsa:2048
    -keyout {{ postgres_cert_path }}/server.key
    -out {{ postgres_cert_path }}/server.crt
    -subj "/CN={{ postgres_domain }}"
  args:
    creates: "{{ postgres_cert_path }}/server.crt"
  when: not pg_cert.stat.exists

- name: Create Supabase files
  template:
    src: "{{ item.src }}.j2"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: "docker-compose-supabase.yml", dest: "/home/{{ deploy_user }}/{{ supabase_path }}/docker-compose-supabase.yml", mode: '0664' }
    - { src: "kong-supabase.yml", dest: "/home/{{ deploy_user }}/{{ supabase_path }}/{{ kong_conf_path }}/kong.yml", mode: '0664' }
    - { src: "env-supabase", dest: "/home/{{ deploy_user }}/{{ supabase_path }}/.env", mode: '0664' }
    - { src: "start-supabase.sh", dest: "/home/{{ deploy_user }}/{{ supabase_path }}/start-supabase.sh", mode: '0755' }

- name: Start Supabase
  command: "bash /home/{{ deploy_user }}/{{ supabase_path }}/start-supabase.sh"
