---

- name: Install UFW
  become: true
  ansible.builtin.package:
    name: ufw
    state: present

- name: Copy UFW script
  become: true
  template:
    src: reset_ufw.sh.j2
    dest: "{{ node_home }}/reset_ufw.sh"
    mode: '0755'

- name: Run UFW script
  become: true
  command: "{{ node_home }}/reset_ufw.sh"
